---
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Released on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]
    steps:
      - name: '📄 Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: '🔤 Set env'
        run: |
          TAG_NAME=${GITHUB_REF#refs/*/}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          VERSION_NAME=${TAG_NAME#v}
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
      - name: '🔧 Install Go'
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"
      - name: '🔧 Install packages'
        shell: bash
        run: ./install.sh
      - name: '📦 Release'
        shell: bash
        run: ./release.sh ${{ env.VERSION_NAME }}
      - name: '🚀 Upload'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PODMAN_TOKEN }}
          file: podman-${{ env.VERSION_NAME }}/release.deb
          asset_name: podman-${{matrix.os}}-amd64.deb
          tag: ${{ github.ref }}
          overwrite: true
          body: "Podman ${{ env.VERSION_NAME }} released"
